// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as CYCLO_VAULT_ADDR,
    BYTECODE_HASH as CYCLO_VAULT_HASH
} from "../generated/candidate/CycloVault.sol";

/// @title LibCycloVaultDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `CycloVault`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibCycloVaultDeploy {
    address constant CYCLO_VAULT_DEPLOYED_ADDRESS = CYCLO_VAULT_ADDR;
    bytes32 constant CYCLO_VAULT_DEPLOYED_CODEHASH = CYCLO_VAULT_HASH;
}
