// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as CYCLO_RECEIPT_ADDR,
    BYTECODE_HASH as CYCLO_RECEIPT_HASH
} from "../generated/candidate/CycloReceipt.sol";

/// @title LibCycloReceiptDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `CycloReceipt`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibCycloReceiptDeploy {
    address constant CYCLO_RECEIPT_DEPLOYED_ADDRESS = CYCLO_RECEIPT_ADDR;
    bytes32 constant CYCLO_RECEIPT_DEPLOYED_CODEHASH = CYCLO_RECEIPT_HASH;
}
