// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as CYCLO_VAULT_ARBITRUM_ADDR,
    BYTECODE_HASH as CYCLO_VAULT_ARBITRUM_HASH
} from "../generated/candidate/CycloVaultArbitrum.sol";

/// @title LibCycloVaultArbitrumDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `CycloVaultArbitrum`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibCycloVaultArbitrumDeploy {
    address constant CYCLO_VAULT_ARBITRUM_DEPLOYED_ADDRESS = CYCLO_VAULT_ARBITRUM_ADDR;
    bytes32 constant CYCLO_VAULT_ARBITRUM_DEPLOYED_CODEHASH = CYCLO_VAULT_ARBITRUM_HASH;
}
