// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as FTSO_V2_LTS_FEED_ORACLE_XRP_USD_ADDR,
    BYTECODE_HASH as FTSO_V2_LTS_FEED_ORACLE_XRP_USD_HASH
} from "../generated/candidate/FtsoV2LTSFeedOracleXrpUsd.sol";

/// @title LibFtsoV2LTSFeedOracleXrpUsdDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `FtsoV2LTSFeedOracleXrpUsd`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibFtsoV2LTSFeedOracleXrpUsdDeploy {
    address constant FTSO_V2_LTS_FEED_ORACLE_XRP_USD_DEPLOYED_ADDRESS = FTSO_V2_LTS_FEED_ORACLE_XRP_USD_ADDR;
    bytes32 constant FTSO_V2_LTS_FEED_ORACLE_XRP_USD_DEPLOYED_CODEHASH = FTSO_V2_LTS_FEED_ORACLE_XRP_USD_HASH;
}
