// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as PYTH_ORACLE_ENA_USD_ADDR,
    BYTECODE_HASH as PYTH_ORACLE_ENA_USD_HASH
} from "../generated/candidate/PythOracleEnaUsd.sol";

/// @title LibPythOracleEnaUsdDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `PythOracleEnaUsd`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibPythOracleEnaUsdDeploy {
    address constant PYTH_ORACLE_ENA_USD_DEPLOYED_ADDRESS = PYTH_ORACLE_ENA_USD_ADDR;
    bytes32 constant PYTH_ORACLE_ENA_USD_DEPLOYED_CODEHASH = PYTH_ORACLE_ENA_USD_HASH;
}
