// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

/// @title LibReleasedSuites
/// @notice Every frozen release this repo has cut, of every contract it
/// deploys: the per-contract released libs concatenated, in declaration
/// order.
///
/// There is one released lib per deployed contract because a release freezes
/// every contract it names into a single tag directory, so a lib that took
/// the record whole would give another contract's snapshot this contract's
/// suite key and collide with its own entry for that tag. This is where
/// those libs meet, and it is emitted from the same list that wrote them --
/// so a contract that is generated, aliased and frozen cannot be missing
/// from the declaration, and a release missing from the declaration is a
/// release every check quietly stops asking about.
library LibReleasedSuites {
    /// Every released suite, in declaration order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        return new DeploySuite[](0);
    }
}
