// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {DeploySuite} from "../abstract/RainDeploySuitesBase.sol";

import {LibCycloReceiptReleased} from "./LibCycloReceiptReleased.sol";

import {LibCycloVaultFlareReleased} from "./LibCycloVaultFlareReleased.sol";

import {LibCycloVaultArbitrumReleased} from "./LibCycloVaultArbitrumReleased.sol";

import {LibSceptreStakedFlrOracleReleased} from "./LibSceptreStakedFlrOracleReleased.sol";

import {LibFtsoV2LTSFeedOracleFlrUsdReleased} from "./LibFtsoV2LTSFeedOracleFlrUsdReleased.sol";

import {LibFtsoV2LTSFeedOracleEthUsdReleased} from "./LibFtsoV2LTSFeedOracleEthUsdReleased.sol";

import {LibFtsoV2LTSFeedOracleXrpUsdReleased} from "./LibFtsoV2LTSFeedOracleXrpUsdReleased.sol";

import {LibFtsoV2LTSFeedOracleJouleUsdReleased} from "./LibFtsoV2LTSFeedOracleJouleUsdReleased.sol";

import {LibPythOracleWethUsdReleased} from "./LibPythOracleWethUsdReleased.sol";

import {LibPythOracleWstethUsdReleased} from "./LibPythOracleWstethUsdReleased.sol";

import {LibPythOracleWbtcUsdReleased} from "./LibPythOracleWbtcUsdReleased.sol";

import {LibPythOracleCbbtcUsdReleased} from "./LibPythOracleCbbtcUsdReleased.sol";

import {LibPythOracleLinkUsdReleased} from "./LibPythOracleLinkUsdReleased.sol";

import {LibPythOracleDotUsdReleased} from "./LibPythOracleDotUsdReleased.sol";

import {LibPythOracleUniUsdReleased} from "./LibPythOracleUniUsdReleased.sol";

import {LibPythOraclePepeUsdReleased} from "./LibPythOraclePepeUsdReleased.sol";

import {LibPythOraclePythUsdReleased} from "./LibPythOraclePythUsdReleased.sol";

import {LibPythOracleEnaUsdReleased} from "./LibPythOracleEnaUsdReleased.sol";

import {LibPythOracleArbUsdReleased} from "./LibPythOracleArbUsdReleased.sol";

import {LibPythOracleXautUsdReleased} from "./LibPythOracleXautUsdReleased.sol";

import {LibTwoPriceOracleV2FlrUsdSflrReleased} from "./LibTwoPriceOracleV2FlrUsdSflrReleased.sol";

/// @title LibReleasedSuites
/// @notice Every frozen release this repo has cut, of every contract it
/// deploys: the per-contract released libs concatenated, in declaration
/// order.
///
/// There is one released lib per deployed contract because a release freezes
/// every contract it names into a single tag directory, so a lib that took
/// the record whole would give another contract's snapshot this contract's
/// suite key and collide with its own entry for that tag. This is where
/// those libs meet, and it is emitted from the same list that wrote them --
/// so a contract that is generated, aliased and frozen cannot be missing
/// from the declaration, and a release missing from the declaration is a
/// release every check quietly stops asking about.
library LibReleasedSuites {
    /// Every released suite, in declaration order.
    /// @return The released suites.
    function releasedSuites() internal pure returns (DeploySuite[] memory) {
        DeploySuite[][] memory released = new DeploySuite[][](21);
        released[0] = LibCycloReceiptReleased.releasedSuites();
        released[1] = LibCycloVaultFlareReleased.releasedSuites();
        released[2] = LibCycloVaultArbitrumReleased.releasedSuites();
        released[3] = LibSceptreStakedFlrOracleReleased.releasedSuites();
        released[4] = LibFtsoV2LTSFeedOracleFlrUsdReleased.releasedSuites();
        released[5] = LibFtsoV2LTSFeedOracleEthUsdReleased.releasedSuites();
        released[6] = LibFtsoV2LTSFeedOracleXrpUsdReleased.releasedSuites();
        released[7] = LibFtsoV2LTSFeedOracleJouleUsdReleased.releasedSuites();
        released[8] = LibPythOracleWethUsdReleased.releasedSuites();
        released[9] = LibPythOracleWstethUsdReleased.releasedSuites();
        released[10] = LibPythOracleWbtcUsdReleased.releasedSuites();
        released[11] = LibPythOracleCbbtcUsdReleased.releasedSuites();
        released[12] = LibPythOracleLinkUsdReleased.releasedSuites();
        released[13] = LibPythOracleDotUsdReleased.releasedSuites();
        released[14] = LibPythOracleUniUsdReleased.releasedSuites();
        released[15] = LibPythOraclePepeUsdReleased.releasedSuites();
        released[16] = LibPythOraclePythUsdReleased.releasedSuites();
        released[17] = LibPythOracleEnaUsdReleased.releasedSuites();
        released[18] = LibPythOracleArbUsdReleased.releasedSuites();
        released[19] = LibPythOracleXautUsdReleased.releasedSuites();
        released[20] = LibTwoPriceOracleV2FlrUsdSflrReleased.releasedSuites();

        uint256 total = 0;
        for (uint256 i = 0; i < released.length; i++) {
            total += released[i].length;
        }

        DeploySuite[] memory suites = new DeploySuite[](total);

        uint256 offset = 0;
        for (uint256 i = 0; i < released.length; i++) {
            for (uint256 j = 0; j < released[i].length; j++) {
                suites[offset + j] = released[i][j];
            }
            offset += released[i].length;
        }

        return suites;
    }
}
