// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as SCEPTRE_STAKED_FLR_ORACLE_ADDR,
    BYTECODE_HASH as SCEPTRE_STAKED_FLR_ORACLE_HASH
} from "../generated/candidate/SceptreStakedFlrOracle.sol";

/// @title LibSceptreStakedFlrOracleDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `SceptreStakedFlrOracle`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibSceptreStakedFlrOracleDeploy {
    address constant SCEPTRE_STAKED_FLR_ORACLE_DEPLOYED_ADDRESS = SCEPTRE_STAKED_FLR_ORACLE_ADDR;
    bytes32 constant SCEPTRE_STAKED_FLR_ORACLE_DEPLOYED_CODEHASH = SCEPTRE_STAKED_FLR_ORACLE_HASH;
}
