// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity ^0.8.25;

// THIS FILE IS AUTOGENERATED BY THE BUILD SCRIPT. DO NOT EDIT BY HAND.

import {
    DEPLOYED_ADDRESS as TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_ADDR,
    BYTECODE_HASH as TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_HASH
} from "../generated/candidate/TwoPriceOracleV2FlrUsdSflr.sol";

/// @title LibTwoPriceOracleV2FlrUsdSflrDeploy
/// @notice The deterministic Zoltu deploy address and code hash of
/// `TwoPriceOracleV2FlrUsdSflr`, aliased from its generated snapshot so that snapshot stays the
/// single source of truth. The import path never moves, so consumers are
/// unaffected by which snapshot it names.
library LibTwoPriceOracleV2FlrUsdSflrDeploy {
    address constant TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_DEPLOYED_ADDRESS = TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_ADDR;
    bytes32 constant TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_DEPLOYED_CODEHASH = TWO_PRICE_ORACLE_V2_FLR_USD_SFLR_HASH;
}
