// SPDX-License-Identifier: LicenseRef-DCL-1.0
// SPDX-FileCopyrightText: Copyright (c) 2020 Rain Open Source Software Ltd
pragma solidity =0.8.25;

import {Test} from "forge-std-1.16.2/src/Test.sol";
import {LibCycloTestProd} from "test/lib/LibCycloTestProd.sol";
import {
    PROD_ARBITRUM_CLONE_FACTORY_ADDRESS_V1,
    PROD_ARBITRUM_CLONE_FACTORY_CODEHASH_V1
} from "src/lib/LibCycloProdCloneFactory.sol";
import {
    PROD_ARBITRUM_CYCLO_RECEIPT_IMPLEMENTATION_V2,
    PROD_ARBITRUM_CYCLO_RECEIPT_CODEHASH_V2,
    PROD_ARBITRUM_RECEIPT_CYWETH_PYTH,
    PROD_ARBITRUM_RECEIPT_CYWSTETH_PYTH,
    PROD_ARBITRUM_RECEIPT_CYWBTC_PYTH,
    PROD_ARBITRUM_RECEIPT_CYCBBTC_PYTH,
    PROD_ARBITRUM_RECEIPT_CYLINK_PYTH,
    PROD_ARBITRUM_RECEIPT_CYDOT_PYTH,
    PROD_ARBITRUM_RECEIPT_CYUNI_PYTH,
    PROD_ARBITRUM_RECEIPT_CYPEPE_PYTH,
    PROD_ARBITRUM_RECEIPT_CYPYTH_PYTH,
    PROD_ARBITRUM_RECEIPT_CYENA_PYTH,
    PROD_ARBITRUM_RECEIPT_CYARB_PYTH,
    PROD_ARBITRUM_RECEIPT_CYXAUT_PYTH
} from "src/lib/LibCycloProdReceipt.sol";
import {
    PROD_ARBITRUM_CYCLO_VAULT_IMPLEMENTATION_V2,
    PROD_ARBITRUM_CYCLO_VAULT_IMPLEMENTATION_V2_CODEHASH,
    PROD_ARBITRUM_VAULT_CYWETH_PYTH,
    PROD_ARBITRUM_VAULT_CYWSTETH_PYTH,
    PROD_ARBITRUM_VAULT_CYWBTC_PYTH,
    PROD_ARBITRUM_VAULT_CYCBBTC_PYTH,
    PROD_ARBITRUM_VAULT_CYLINK_PYTH,
    PROD_ARBITRUM_VAULT_CYDOT_PYTH,
    PROD_ARBITRUM_VAULT_CYUNI_PYTH,
    PROD_ARBITRUM_VAULT_CYPEPE_PYTH,
    PROD_ARBITRUM_VAULT_CYPYTH_PYTH,
    PROD_ARBITRUM_VAULT_CYENA_PYTH,
    PROD_ARBITRUM_VAULT_CYARB_PYTH,
    PROD_ARBITRUM_VAULT_CYXAUT_PYTH
} from "src/lib/LibCycloProdVault.sol";
import {
    PROD_PYTH_ORACLE_WETH_USD_ARBITRUM,
    PYTH_ORACLE_WETH_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_WSTETH_USD_ARBITRUM,
    PYTH_ORACLE_WSTETH_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_WBTC_USD_ARBITRUM,
    PYTH_ORACLE_WBTC_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_CBBTC_USD_ARBITRUM,
    PYTH_ORACLE_CBBTC_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_LINK_USD_ARBITRUM,
    PYTH_ORACLE_LINK_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_DOT_USD_ARBITRUM,
    PYTH_ORACLE_DOT_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_UNI_USD_ARBITRUM,
    PYTH_ORACLE_UNI_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_PEPE_USD_ARBITRUM,
    PYTH_ORACLE_PEPE_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_PYTH_USD_ARBITRUM,
    PYTH_ORACLE_PYTH_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_ENA_USD_ARBITRUM,
    PYTH_ORACLE_ENA_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_ARB_USD_ARBITRUM,
    PYTH_ORACLE_ARB_USD_ARBITRUM_CODEHASH,
    PROD_PYTH_ORACLE_XAUT_USD_ARBITRUM,
    PYTH_ORACLE_XAUT_USD_ARBITRUM_CODEHASH
} from "src/lib/LibCycloProdOracle.sol";

/// @title CycloProdArbitrumTest
/// @notice Every Arbitrum production deployment still runs the pinned code.
contract CycloProdArbitrumTest is Test {
    function setUp() external {
        LibCycloTestProd.createSelectForkArbitrum(vm);
    }

    function testProdCloneFactory() external view {
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_ARBITRUM_CLONE_FACTORY_ADDRESS_V1, PROD_ARBITRUM_CLONE_FACTORY_CODEHASH_V1
        );
    }

    function checkReceipt(address proxy) internal view {
        LibCycloTestProd.checkCBORTrimmedBytecodeHashBy1167Proxy(
            proxy, PROD_ARBITRUM_CYCLO_RECEIPT_IMPLEMENTATION_V2, PROD_ARBITRUM_CYCLO_RECEIPT_CODEHASH_V2
        );
    }

    function testProdReceipts() external view {
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYWETH_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYWSTETH_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYWBTC_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYCBBTC_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYLINK_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYDOT_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYUNI_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYPEPE_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYPYTH_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYENA_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYARB_PYTH);
        checkReceipt(PROD_ARBITRUM_RECEIPT_CYXAUT_PYTH);
    }

    function checkVault(address proxy) internal view {
        LibCycloTestProd.checkCBORTrimmedBytecodeHashBy1167Proxy(
            proxy, PROD_ARBITRUM_CYCLO_VAULT_IMPLEMENTATION_V2, PROD_ARBITRUM_CYCLO_VAULT_IMPLEMENTATION_V2_CODEHASH
        );
    }

    function testProdVaults() external view {
        checkVault(PROD_ARBITRUM_VAULT_CYWETH_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYWSTETH_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYWBTC_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYCBBTC_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYLINK_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYDOT_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYUNI_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYPEPE_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYPYTH_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYENA_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYARB_PYTH);
        checkVault(PROD_ARBITRUM_VAULT_CYXAUT_PYTH);
    }

    function testProdPythOracles() external view {
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_WETH_USD_ARBITRUM, PYTH_ORACLE_WETH_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_WSTETH_USD_ARBITRUM, PYTH_ORACLE_WSTETH_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_WBTC_USD_ARBITRUM, PYTH_ORACLE_WBTC_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_CBBTC_USD_ARBITRUM, PYTH_ORACLE_CBBTC_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_LINK_USD_ARBITRUM, PYTH_ORACLE_LINK_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_DOT_USD_ARBITRUM, PYTH_ORACLE_DOT_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_UNI_USD_ARBITRUM, PYTH_ORACLE_UNI_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_PEPE_USD_ARBITRUM, PYTH_ORACLE_PEPE_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_PYTH_USD_ARBITRUM, PYTH_ORACLE_PYTH_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_ENA_USD_ARBITRUM, PYTH_ORACLE_ENA_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_ARB_USD_ARBITRUM, PYTH_ORACLE_ARB_USD_ARBITRUM_CODEHASH
        );
        LibCycloTestProd.checkCBORTrimmedBytecodeHash(
            PROD_PYTH_ORACLE_XAUT_USD_ARBITRUM, PYTH_ORACLE_XAUT_USD_ARBITRUM_CODEHASH
        );
    }
}
